spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/fans?useSSL=false&characterEncoding=UTF-8&autoCommit=true&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      validation-query: select 1

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    open-in-view: true

  redis:
    host: 127.0.0.1
    port: 6379
